# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importClassesFrom Matrix dgTMatrix
graperCpp_dense_nf <- function(X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB) {
    .Call('_iBAG_graperCpp_dense_nf', PACKAGE = 'iBAG', X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB)
}

#' @importClassesFrom Matrix dgTMatrix
graperCpp_dense_ff <- function(X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB, mu_init) {
    .Call('_iBAG_graperCpp_dense_ff', PACKAGE = 'iBAG', X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB, mu_init)
}

#' @importClassesFrom Matrix dgTMatrix
graperCpp_sparse_ff <- function(X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init) {
    .Call('_iBAG_graperCpp_sparse_ff', PACKAGE = 'iBAG', X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init)
}

#' @importClassesFrom Matrix dgTMatrix
graperCpp_sparse_ff_nogamma <- function(X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init) {
    .Call('_iBAG_graperCpp_sparse_ff_nogamma', PACKAGE = 'iBAG', X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init)
}

#' @importClassesFrom Matrix dgTMatrix
graperCpp_logistic_nf <- function(X, y, annot, g, NoPerGroup, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB) {
    .Call('_iBAG_graperCpp_logistic_nf', PACKAGE = 'iBAG', X, y, annot, g, NoPerGroup, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB)
}

graperCpp_logistic_ff <- function(X, y, annot, g, NoPerGroup, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB, mu_init, intercept) {
    .Call('_iBAG_graperCpp_logistic_ff', PACKAGE = 'iBAG', X, y, annot, g, NoPerGroup, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB, mu_init, intercept)
}

#' @importClassesFrom Matrix dgTMatrix
graperCpp_sparse_logistic_ff <- function(X, y, annot, g, NoPerGroup, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init, intercept) {
    .Call('_iBAG_graperCpp_sparse_logistic_ff', PACKAGE = 'iBAG', X, y, annot, g, NoPerGroup, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init, intercept)
}

